# Generated by Django 6.0.5 on 2026-05-16 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('event_type', models.CharField(choices=[('birthday', 'День Рождения'), ('newyear', 'Новый Год'), ('wedding', 'Свадьба'), ('holiday', 'Праздник'), ('noreason', 'Без повода')], default='birthday', max_length=20, verbose_name='Тип события')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('privacy', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=10, verbose_name='Приватность')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('finished', 'Завершён'), ('archived', 'Архивный')], default='active', max_length=10, verbose_name='Статус')),
                ('share_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вишлист',
                'verbose_name_plural': 'Вишлисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('books', 'Книги'), ('clothes', 'Одежда'), ('home', 'Дом'), ('toys', 'Игрушки'), ('certificate', 'Сертификат'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена (₽)')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('reserved', 'Зарезервирован'), ('gifted', 'Подарен')], default='free', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_gifts', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.wishlist')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
