# Generated by Django 6.0.5 on 2026-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения'),
        ),
    ]
