# Generated by Django 6.0.5 on 2026-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gift_image_gift_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='reserve_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий дарителя'),
        ),
    ]
